In [11]:
import numpy as np
import matplotlib as pb
import matplotlib.pyplot as plt

In [17]:
# section 4.2        code 3,3
#Linear weighted combination

In [18]:
l1 = 1
l2 = 2
l3 = -3
v1 =np.array([4,5,1])
v2 =np.array([-4,0,-4]) 
v3 =np.array([1,3,2])
l1 * v1 + l2*v2+ l3*v3



array([ -7,  -4, -13])

In [19]:
# the outer product
# indicates that the dot product (vTw) is a 1×1 array
#(just a single number; a scalar) whereas the outer product (vwT)
#is a matrix whose sizes are defined by the number of elements 

In [20]:
v1=np.array([2,5,4,7])
v2=np.array([4,1,0,2])
op=np.outer(v1,v2)
print(op)

[[ 8  2  0  4]
 [20  5  0 10]
 [16  4  0  8]
 [28  7  0 14]]
